version: '3.7'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: bash -c "alembic upgrade head && gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

volumes:
  pgdata:
